DROP TABLE IF EXISTS `character_npcbot`;
CREATE TABLE `character_npcbot` (
  `owner` int(10) default NULL,
  `entry` int(10) default NULL,
  `race` tinyint(3) default NULL,
  `class` tinyint(3) default NULL,
  `istank` tinyint(3) default NULL,
  `equipMhEx` int(10) default NULL,
  `equipOhEx` int(10) default NULL,
  `equipRhEx` int(10) default NULL,
  `equipHead` int(10) default NULL,
  `equipShoulders` int(10) default NULL,
  `equipChest` int(10) default NULL,
  `equipWaist` int(10) default NULL,
  `equipLegs` int(10) default NULL,
  `equipFeet` int(10) default NULL,
  `equipWrist` int(10) default NULL,
  `equipHands` int(10) default NULL,
  `equipBack` int(10) default NULL,
  `equipBody` int(10) default NULL,
  `equipFinger1` int(10) default NULL,
  `equipFinger2` int(10) default NULL,
  `equipTrinket1` int(10) default NULL,
  `equipTrinket2` int(10) default NULL,
  `equipNeck` int(10) default NULL,
  `active` tinyint(3) default NULL,
  PRIMARY KEY  (`owner`,`entry`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
